### ISSUE TITLE
Support for ASCII STL

### ISSUE THREAD

**Issue by Axford** [mkeeter/fstl#1]
Hi

Would be great to add support for ASCII STL, mainly because it's what OpenSCAD generates.  

thanks
D

**Comment by marmilicious** [comment]
I too was wondering if you could add ASCII STL support.  Thanks for this quick little program Matthew.

**Comment by rahji** [comment]
FYI: this ruby script seems to work well for converting back and forth between binary and ASCII... http://www.thingiverse.com/thing:39655/#files

**Comment by DeveloperPaul123** [comment]
I've added ASCII support in my fork [here](https://github.com/DeveloperPaul123/fstl). I've created a pull request, so hopefully changes will be merged. Note that currently the file will be assumed to be ASCII if it begins with the "solid" keyword. I'll be making changes as need be to make this work better.

**Comment by mkeeter** [comment]
ASCII `.stl` files are supported in the new release ([`0.9.3`](https://github.com/mkeeter/fstl/releases/tag/v0.9.3)).  Please re-open if you're having any issues.
