### ISSUE TITLE
How to improve for multiple objects? 

### ISSUE THREAD

**Issue by esacape3d** [mkeeter/fstl#11]
It may not a simple task, but how can I improve the program to accept multiple objects and display them? I understand that the code utilizes QGLBuffer for faster rendering, but don't know how. Can I know rough algorithm for this? Thanks for a nice code.

**Comment by DeveloperPaul123** [comment]
How do you envision this working? Would it render the items side by side? On top of each other?

**Comment by DeveloperPaul123** [comment]
@esacape3d Any further feedback?

**Comment by DeveloperPaul123** [comment]
@esacape3d Any further feedback?
