### ISSUE TITLE
Is this a snapshot or model viewer?

### ISSUE THREAD

**Issue by echrisinger** [mkeeter/fstl#19]
Hey, just a quick question. Working on using this for a project, but I'm looking to take snapshots of models, not have them rotating in a program. Does this produce snapshots of models? The renderings look great.

Edit: seems like a model viewer. Any thoughts of building in a snapshot tool? I may be working on one.

**Comment by mkeeter** [comment]
Yup, this is a pure model viewer.  What would a snapshot tool look like, besides just opening the model and taking a screenshot of the `fstl` window?

**Comment by DeveloperPaul123** [comment]
@echrisinger The ability to save screenshots has been added to the `0.9.4` release if you're still interested.
