### ISSUE TITLE
Canvas stays small, rest of window is black

### ISSUE THREAD

**Issue by franciscod** [mkeeter/fstl#2]
Somehow, the rendered canvas doesn't scale to cover the entire window, instead it stays small at the corner:

![1432913739](https://cloud.githubusercontent.com/assets/726447/7886384/1e67745a-0600-11e5-840b-1bb77f1cccb9.png)
![1432913743](https://cloud.githubusercontent.com/assets/726447/7886385/1e6cf858-0600-11e5-95a9-38870e4009e5.png)
![1432913749](https://cloud.githubusercontent.com/assets/726447/7886386/1e6e5aa4-0600-11e5-99fb-684ca446c8f7.png)

I've compiled fstl as following:
```
mkdir build
cd build
qmake ../qt/fstl.pro
make
./fstl
```

```
QMake version 3.0
Using Qt version 5.4.1 in /usr/lib
```

(Loading the project with QtCreator and building it from there yields the same issue)

I've tried tinkering with the transform and view matrices with no results :(

**Comment by rahji** [comment]
I have the same problem if I run the program with the name of an .stl file from the command line. If I then open the [same] file with the File | Open menu item, it looks correct.

**Comment by nmaggioni** [comment]
+1 for this issue, on HiDPI display.

**Comment by graywolf2** [comment]
I had the same problem. I fixed it by delaying of startup stl file load by 500 milliseconds.
The App constructor I made as:
App::App(int &argc, char *argv[]) :
	QApplication(argc, argv), window(new Window())
{
    window->show();
    QTimer::singleShot(500, this, SLOT(load_stl()));
}

Also I made the load_stl slot in App class:
void App::load_stl()
{
	if (arguments().count() > 1) window->load_stl(arguments()[1]);
	else window->load_stl(":gl/sphere.stl");
}

Before fix:
![screenshot at 2016-09-14 17-46-50](https://cloud.githubusercontent.com/assets/12239412/18518029/11be9482-7aa7-11e6-8453-38ec4b3f5705.png)

After fix:
![screenshot at 2016-09-14 18-00-28](https://cloud.githubusercontent.com/assets/12239412/18518069/30e505ee-7aa7-11e6-9fcc-a8ff4275de66.png)

I attached the fixed app.h and app.cpp files.
[fstl_fix.zip](https://github.com/mkeeter/fstl/files/472420/fstl_fix.zip)

**Comment by franciscod** [comment]
Thanks, @graywolf2!

It appears that your fix does indeed work, but as soon as you resize the window, the canvas doesn't scale with it :(

Nonetheless, we are (maybe?) closer now!
