### ISSUE TITLE
compile problem under linux

### ISSUE THREAD

**Issue by ruenahcmohr** [mkeeter/fstl#25]
I'v never yet had a qt project compile without issues....
Maybe this is something simple.

zippo:/files/programming/src/fstl/fstl/build# qmake ../qt/fstl.pro 
zippo:/files/programming/src/fstl/fstl/build# make -j8
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o app.o ../src/app.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o main.o ../src/main.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o canvas.o ../src/canvas.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o mesh.o ../src/mesh.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o glmesh.o ../src/glmesh.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o loader.o ../src/loader.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o window.o ../src/window.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o backdrop.o ../src/backdrop.cpp
In file included from /usr/include/c++/4.7/future:35:0,
                 from ../src/loader.cpp:1:
/usr/include/c++/4.7/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
/usr/lib/i386-linux-gnu/qt4/bin/moc -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. ../src/app.h -o moc_app.cpp
/usr/lib/i386-linux-gnu/qt4/bin/moc -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. ../src/canvas.h -o moc_canvas.cpp
../src/canvas.h:64: Warning: Property declaration perspective has no READ accessor function. The property will be invalid.
/usr/lib/i386-linux-gnu/qt4/bin/moc -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. ../src/loader.h -o moc_loader.cpp
/usr/lib/i386-linux-gnu/qt4/bin/moc -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. ../src/window.h -o moc_window.cpp
/usr/lib/i386-linux-gnu/qt4/bin/rcc -name qt ../qt/qt.qrc -o qrc_qt.cpp
/usr/lib/i386-linux-gnu/qt4/bin/rcc -name gl ../gl/gl.qrc -o qrc_gl.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o moc_app.o moc_app.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o moc_canvas.o moc_canvas.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o moc_loader.o moc_loader.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o moc_window.o moc_window.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o qrc_qt.o qrc_qt.cpp
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I../qt -I. -o qrc_gl.o qrc_gl.cpp
In file included from ../src/loader.h:6:0,
                 from ../src/window.cpp:7:
../src/mesh.h:12:30: error: expected ',' or '...' before '&&' token
In file included from /usr/include/qt4/QtCore/QFileSystemWatcher:1:0,
                 from ../src/window.h:6,
                 from ../src/window.cpp:5:
/usr/include/qt4/QtCore/qfilesystemwatcher.h: In constructor 'Window::Window(QWidget*)':
/usr/include/qt4/QtCore/qfilesystemwatcher.h:76:10: error: 'void QFileSystemWatcher::fileChanged(const QString&)' is protected
../src/window.cpp:36:52: error: within this context
../src/window.cpp:37:54: error: no matching function for call to 'Window::connect(QFileSystemWatcher*&, void (QFileSystemWatcher::*)(const QString&), Window* const, void (Window::*)(const QString&))'
../src/window.cpp:37:54: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QFileSystemWatcher::*)(const QString&)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QFileSystemWatcher::*)(const QString&)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QFileSystemWatcher::*)(const QString&)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qmenu.h:48:0,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qaction.h:228:10: error: 'void QAction::triggered(bool)' is protected
../src/window.cpp:40:45: error: within this context
../src/window.cpp:41:44: error: no matching function for call to 'Window::connect(QAction* const&, void (QAction::*)(bool), Window* const, void (Window::*)())'
../src/window.cpp:41:44: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qmenu.h:48:0,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qaction.h:228:10: error: 'void QAction::triggered(bool)' is protected
../src/window.cpp:44:45: error: within this context
../src/window.cpp:45:42: error: no matching function for call to 'Window::connect(QAction* const&, void (QAction::*)(bool), Window* const, bool (QWidget::*)())'
../src/window.cpp:45:42: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qmenu.h:48:0,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qaction.h:228:10: error: 'void QAction::triggered(bool)' is protected
../src/window.cpp:50:51: error: within this context
../src/window.cpp:51:51: error: no matching function for call to 'Window::connect(QAction* const&, void (QAction::*)(bool), Window* const, void (Window::*)(bool))'
../src/window.cpp:51:51: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qmenu.h:48:0,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qaction.h:228:10: error: 'void QAction::triggered(bool)' is protected
../src/window.cpp:55:47: error: within this context
../src/window.cpp:56:46: error: no matching function for call to 'Window::connect(QAction* const&, void (QAction::*)(bool), Window* const, void (Window::*)())'
../src/window.cpp:56:46: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qmenu.h:48:0,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qaction.h:228:10: error: 'void QAction::triggered(bool)' is protected
../src/window.cpp:58:46: error: within this context
../src/window.cpp:59:45: error: no matching function for call to 'Window::connect(QAction* const&, void (QAction::*)(bool), Window* const, void (Window::*)())'
../src/window.cpp:59:45: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qmenu.h:48:0,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qaction.h:228:10: error: 'void QAction::triggered(bool)' is protected
../src/window.cpp:61:59: error: within this context
../src/window.cpp:62:52: error: no matching function for call to 'Window::connect(QAction* const&, void (QAction::*)(bool), Window* const, void (Window::*)())'
../src/window.cpp:62:52: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QAction::*)(bool)' to 'const char*'
In file included from /usr/include/qt4/QtGui/qaction.h:255:0,
                 from /usr/include/qt4/QtGui/qmenu.h:48,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qactiongroup.h:95:10: error: 'void QActionGroup::triggered(QAction*)' is protected
../src/window.cpp:63:57: error: within this context
../src/window.cpp:64:51: error: no matching function for call to 'Window::connect(QActionGroup* const&, void (QActionGroup::*)(QAction*), Window* const, void (Window::*)(QAction*))'
../src/window.cpp:64:51: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from 'void (QActionGroup::*)(QAction*)' to 'const char*'
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from 'void (QActionGroup::*)(QAction*)' to 'const QMetaMethod&'
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from 'void (QActionGroup::*)(QAction*)' to 'const char*'
../src/window.cpp:68:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:68:10: error: 'file_menu' does not name a type
../src/window.cpp:69:5: error: 'file_menu' was not declared in this scope
../src/window.cpp:76:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:76:10: error: 'view_menu' does not name a type
../src/window.cpp:77:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:77:10: error: 'projection_menu' does not name a type
../src/window.cpp:78:5: error: 'projection_menu' was not declared in this scope
../src/window.cpp:80:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:80:10: error: 'projections' does not name a type
../src/window.cpp:81:10: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:81:15: error: 'p' does not name a type
../src/window.cpp:81:58: error: expected ';' before ')' token
../src/window.cpp:81:58: error: expected primary-expression before ')' token
../src/window.cpp:81:58: error: expected ';' before ')' token
../src/window.cpp:83:9: error: 'projections' was not declared in this scope
../src/window.cpp:83:32: error: 'p' was not declared in this scope
../src/window.cpp:87:5: error: 'projections' was not declared in this scope
In file included from /usr/include/qt4/QtGui/qaction.h:255:0,
                 from /usr/include/qt4/QtGui/qmenu.h:48,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
/usr/include/qt4/QtGui/qactiongroup.h:95:10: error: 'void QActionGroup::triggered(QAction*)' is protected
../src/window.cpp:88:50: error: within this context
../src/window.cpp:91:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:91:10: error: 'help_menu' does not name a type
../src/window.cpp:92:5: error: 'help_menu' was not declared in this scope
../src/window.cpp: In member function 'void Window::set_watched(const QString&)':
../src/window.cpp:161:11: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:161:16: error: 'files' does not name a type
../src/window.cpp:162:9: error: 'files' was not declared in this scope
../src/window.cpp:169:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:169:10: error: 'recent' does not name a type
../src/window.cpp:170:11: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:170:16: error: 'f' does not name a type
../src/window.cpp:171:5: error: 'recent' was not declared in this scope
../src/window.cpp:171:22: error: 'f' was not declared in this scope
../src/window.cpp: In member function 'void Window::rebuild_recent_files()':
../src/window.cpp:226:11: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:226:16: error: 'actions' does not name a type
../src/window.cpp:227:10: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:227:15: error: 'a' does not name a type
../src/window.cpp:231:5: error: expected ';' before 'recent_files'
../src/window.cpp:231:25: error: could not convert '((QMenu*)((Window*)this)->Window::recent_files)->QMenu::clear()' from 'void' to 'bool'
../src/window.cpp:233:5: error: expected primary-expression before 'for'
../src/window.cpp:233:5: error: expected ')' before 'for'
../src/window.cpp:233:10: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:233:15: error: 'f' does not name a type
../src/window.cpp:240:5: error: expected ';' before 'if'
../src/window.cpp:240:5: error: expected primary-expression before 'if'
../src/window.cpp:240:5: error: expected ';' before 'if'
../src/window.cpp:240:5: error: expected primary-expression before 'if'
../src/window.cpp:240:5: error: expected ')' before 'if'
../src/window.cpp:242:9: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:242:14: error: 'a' does not name a type
../src/window.cpp:243:33: error: 'a' was not declared in this scope
../src/window.cpp: In member function 'void Window::on_reload()':
../src/window.cpp:252:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
../src/window.cpp:252:10: error: 'fs' does not name a type
../src/window.cpp:253:9: error: 'fs' was not declared in this scope
In file included from /usr/include/qt4/QtCore/QThread:1:0,
                 from ../src/loader.h:4,
                 from ../src/window.cpp:7:
/usr/include/qt4/QtCore/qthread.h: In member function 'bool Window::load_stl(const QString&, bool)':
/usr/include/qt4/QtCore/qthread.h:105:10: error: 'void QThread::started()' is protected
../src/window.cpp:266:30: error: within this context
../src/window.cpp:267:42: error: no matching function for call to 'Window::connect(Loader*&, void (QThread::*)(), Window* const, void (Window::*)())'
../src/window.cpp:267:42: note: candidates are:
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmenu.h:45,
                 from /usr/include/qt4/QtGui/qmenubar.h:45,
                 from /usr/include/qt4/QtGui/QMenuBar:1,
                 from ../src/window.cpp:1:
.
.
.
ok just tell me if you want more cause theres a lot of it.

**Comment by DeveloperPaul123** [comment]
It looks like you're using Qt4, and as noted in #7, `fstl` requires Qt5.

**Comment by mkeeter** [comment]
Yup, @DeveloperPaul123 is correct.  I've updated the README to indicate this; feel free to open a new issue if you're having problems building with Qt 5.

**Comment by mkeeter** [comment]
FYI @DeveloperPaul123, I've given you commit access to the repo, since you're doing a better job replying to issues than I am 😃 

Please open PRs if you've got major changes to review, but otherwise, feel free to make updates and fixes independently.

**Comment by ruenahcmohr** [comment]
ah good show rue, an ID 10-T error...
I'm assembling the error it gave me with qt5 installed....

**Comment by DeveloperPaul123** [comment]
@mkeeter Sweet thanks! Always happy to help.
