### ISSUE TITLE
Warning When Configuring on Windows 10 with CMake 3.10.2

### ISSUE THREAD

**Issue by DeveloperPaul123** [mkeeter/fstl#27]
When configuring on windows 10 using the latest version of CMake (`3.10.2`) a warning is thrown because of the having `CMAKE_AUTOMOC` and `CMAKE_AUTOUIC` to on without explicitly setting the CMake policy `CMP0071`: 

![image](https://user-images.githubusercontent.com/6591180/36239280-3490a6e0-11d6-11e8-8ccc-c0b80a3eaf73.png)

We can fix this multiple ways:
1. Explicitly set `CMP0071` 
2. Turn `CMAKE_AUTOMOC` and `CMAKE_AUTOUIC` off and instead use `qt5_wrap_cpp` and `qt5_wrap_ui`. 

@mkeeter What are your thoughts?

**Comment by mkeeter** [comment]
Usually, when I run into these issues, I set whatever CMake policy they're asking for (`cmake_policy(SET CMP0071 NEW)` in this case).

If that doesn't break anything, it's the simplest solution.

**Comment by DeveloperPaul123** [comment]
@mkeeter 
According to the warning, setting that policy to `NEW` means those files _will_ be processed by `automoc` and `autouic`. We don't want this right since those files are generated by `qt5_wrap_qrc`, right?
