### ISSUE TITLE
Models are upside down

### ISSUE THREAD

**Issue by bionik** [mkeeter/fstl#3]
All my models are upside down. I wish I had an option to change the default orientation as upside down.

**Comment by aiQon** [comment]
can confirm that on latest master branch and mac os el capitan with qt 5

**Comment by aiQon** [comment]
btw:
to be able to tilt more and spin models upside down use this in canvas.cpp

```
void Canvas::mouseMoveEvent(QMouseEvent* event)
{
    auto p = event->pos();
    auto d = p - mouse_pos;

    if (event->buttons() & Qt::LeftButton)
    {
        yaw = yaw + d.x(); //fmod(yaw - d.x(), 360);
        tilt = tilt - d.y();//fmax(0, fmin(180, tilt - d.y()));
        update();
    }
    else if (event->buttons() & Qt::RightButton)
    {
        center = transform_matrix().inverted() *
                 view_matrix().inverted() *
                 QVector3D(-d.x() / (0.5*width()),
                            d.y() / (0.5*height()), 0);
        update();
    }
    mouse_pos = p;
}
```

Notice the yaw and tilt assignments

**Comment by nmaggioni** [comment]
+1 for @aiQon solution, it should be merged - why shouldn't we be able to rotate model upside down, anyway?

**Comment by bionik** [comment]
The issue seems to be fixed now, except that x-axis is mirrored. I fixed it in this pull request: https://github.com/mkeeter/fstl/pull/14
