### ISSUE TITLE
Most ASCII STL without solid's name won't load

### ISSUE THREAD

**Issue by Grawp** [mkeeter/fstl#33]
https://github.com/mkeeter/fstl/blob/d021118ee2f162c2e487c5454f51589d1797fdc1/src/loader.cpp#L120

At least OpenSCAD and FreeCAD (and probably other applications capable of producing ASCII STL) do not place space after the word *solid* when it's not followed by name.

(The only article saying that the space should always follow the word *solid* is the one on Wikipedia and I haven't *yet* found such information in any of the cited sources.)

**Comment by mkeeter** [comment]
Okay, I loosened the requirement for an STL to be recognized as ASCII.

There's no formal spec for the format, so I went by the Wikipedia description, but might as well be generous with what we accept...
