### ISSUE TITLE
Accidental CMakeLists change

### ISSUE THREAD

**Issue by mboerwinkle** [mkeeter/fstl#36]
I was working on a fix for a cmake warning with this commit: https://github.com/mboerwinkle/fstl/commit/7a1e6385e80d2582438911ced03d269a8d2c1df4

This commit modified my existing pull request on mkeeter/fstl. A few minutes later, @mkeeter merged the pull request, inadvertently including my untested (it works for me, but I hadn't submitted it for review yet) modification to CMakeLists.txt.

I wanted to make sure this did not go unnoticed and cause problems for someone.

Martin

**Comment by mkeeter** [comment]
Thanks for the warning!  I'll leave it in for now; if anyone has trouble on Linux, we can revisit it.
