### ISSUE TITLE
feature request:  rmb save as png

### ISSUE THREAD

**Issue by kelargo** [mkeeter/fstl#45]
A nice feature to have:  to be able to safe the viewed image as a graphics png file. 

right mouse button, save as, stl_filename.png  or something like that. 

thanks

**Comment by DeveloperPaul123** [comment]
I've implemented this [here](https://github.com/DeveloperPaul123/fstl/tree/feature/save-screen-shot).

Below is a screen shot:

![image](https://user-images.githubusercontent.com/6591180/66691714-4af68500-ec66-11e9-9eef-41f6fe24b56d.png)

And the resulting saved image

<img width="300" alt="test_1" src="https://user-images.githubusercontent.com/6591180/66691722-5944a100-ec66-11e9-8144-2af26c78b924.png">

@mkeeter Any feedback on option location/label?

**Comment by mkeeter** [comment]
Seems reasonable!

**Comment by kelargo** [comment]
Awesome! Thank you.

**Comment by DeveloperPaul123** [comment]
I referenced the wrong issue in the commit message for #47. This issue is now resolved.
