### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ericonr** [mkeeter/fstl#50]
Hey there! This is a pretty cool piece of software, and it also looks extremely good. I'd really like to package it for Void Linux, but unfortunately the latest release is quite a bit buggy (I had to compile master to actually get it to work).

Do you think it would be possible to make a release? If you need any help, I can try to aid you.

**Comment by DeveloperPaul123** [comment]
@mkeeter I can do this if you want. Lmk what release number.

**Comment by mkeeter** [comment]
Sounds good, let's do 0.9.4.

Sadly, my Windows VM + static Qt build has been lost to the ages, so it's a pain for me to make a standalone Windows build.

**Comment by DeveloperPaul123** [comment]
I can make a standalone build for Windows and Linux (ubuntu) as well as an installer. Is that ok? 

Also, we should use the latest Qt version (5.14), right?

**Comment by mkeeter** [comment]
Yup, that would be great!

**Comment by ericonr** [comment]
Thanks for the quick response! If you need anything lmk

**Comment by DeveloperPaul123** [comment]
@mkeeter I created a draft release if you want to take a look before publishing.

**Comment by mkeeter** [comment]
I tried to make a Mac `.dmg` using `cpack`, since `app/package.sh` has been broken by other changes in the `CMakeLists.txt`.  This didn't work, so I commited a fix (633504e693606c0cc7d88e45ae90f11ef1c89b7f) for the packaging script and attached a DMG to the draft release.

**Comment by DeveloperPaul123** [comment]
Awesome, @ericonr new release is up and available now 👍

**Comment by ericonr** [comment]
Thank you very much @DeveloperPaul123  and @mkeeter !

Take care :)
