### ISSUE TITLE
No way to disable obnoxious file warning after opening every file

### ISSUE THREAD

**Issue by fake-name** [mkeeter/fstl#57]
Every time I open a STL file generated by solidworks, `fstl` pops up a pointless warning dialog:

------

<b>Warning:</b><br>This <code>.stl</code> file begins with <code>solid </code>but appears to be a binary file.<br><code>fstl</code> loaded it, but other programs may be confused by this file.

------

I've used solidworks to generate hundreds of STLs for use with probably dozens of other pieces of software, and never had issues (aside from the usual mm/inch confusion). Furthermore, this dialog is modal and cannot be prevented from popping up. 

From the [original STL specification](https://www.fabbers.com/tech/STL_Format), the first 80 bytes are specified as "Header. No special significance". If there's software out there that's making assumptions about the contents of the file based on the first 80 bytes, and not using further heuristics to validate that assumption, that other piece of software is broken. It shouldn't be something `fstl` bothers me about.

**Comment by DeveloperPaul123** [comment]
I think the original intention was to differentiate between ASCII and binary `*.stl` files.

**Comment by mkeeter** [comment]
Fixed!

**Comment by fake-name** [comment]
> I think the original intention was to differentiate between ASCII and binary *.stl files.

Yeah, but looking for `solid` in the header *doesn't do that*.
