### ISSUE TITLE
fstl cannot open .STL files

### ISSUE THREAD

**Issue by MarcelRobitaille** [mkeeter/fstl#59]
By that, I mean, if the extension is uppercase, fstl refuses to open the file. Same thing for the "File open" menu; it won't show files with uppercase extensions.

I hate uppercase extensions as much as the next guy, but this is inconvenient when you download a git repo with .STL files.

**Comment by DeveloperPaul123** [comment]
I can look into this.

> but this is inconvenient when you download a git repo with .STL files.

Can you provide an example? 

In the mean time you could use something like Power Toy's rename feature to easily change the extensions all at once.

**Comment by MarcelRobitaille** [comment]
[Here is the repo I downloaded](https://github.com/Opentrons/ot2/tree/master/reference-model/STL)

Yes, I have renamed the files for now.

Thanks for looking into it. :grinning:
