### ISSUE TITLE
make fails on Ubuntu 14.04LTS + qt4-dev-tools

### ISSUE THREAD

**Issue by marsanyi** [mkeeter/fstl#7]
Compilation errors running "make" on system.  Installed qt4-dev-tools, using gcc 4.8.4 stock install on Ubuntu 14.04LTS.  Output attached.
[errs.txt](https://github.com/mkeeter/fstl/files/303396/errs.txt)

**Comment by marsanyi** [comment]
(caveat: I'm not a QT developer)

**Comment by mkeeter** [comment]
`fstl` requires Qt 5, since Qt 4 doesn't have the right OpenGL API.  On 14.04, you'll have to download it manually from [qt.io](https://www.qt.io), but in the latest LTS it's built-in.

**Comment by DeveloperPaul123** [comment]
@mkeeter Can this be closed?

**Comment by mkeeter** [comment]
Yup!
